if obj_progress.play_lobby_cutscene_1 {
	t_scene_info = [
		[cutscene_wait,0.5],
		[cutscene_instance_destroy,inst_3155A79F],
		[cutscene_instance_destroy,inst_278819CB],
		[cutscene_play_animation,inst_30E6BD8B,spr_elevator,noone],
		[cutscene_change_value,inst_30E6BD8B,"close_timer",120],
		[cutscene_move_character,obj_player,0,14,true,0.40,spr_player_run,spr_player_idle],
		[cutscene_move_character,obj_player,212,204,false,0.4,spr_player_run,spr_player_idle],
		[cutscene_move_character,obj_player,0,-8,true,0.40,spr_player_run,spr_player_idle],
		[cutscene_wait,0.5],
		[cutscene_change_camera_position,252,200],
		[cutscene_wait,1],
		[cutscene_instance_create,252,190,"enemies",obj_mimic],
		[cutscene_play_animation,inst_452E13EA,spr_elevator,noone],
		[cutscene_change_value,inst_452E13EA,"close_timer",120],
		[cutscene_move_character,obj_mimic,0,18,true,0.20,spr_mimic1_walk,spr_mimic1_idle],
		[cutscene_wait,1],
		[cutscene_change_xscale,obj_mimic],
		[cutscene_wait,0.5],
		[cutscene_change_xscale,obj_mimic],
		[cutscene_wait,0.5],
		[cutscene_move_character,obj_mimic,100,0,true,0.40,spr_mimic1_run,spr_mimic1_idle],
		[cutscene_instance_destroy,obj_mimic],
		[cutscene_wait,0.5],
		[cutscene_change_camera_target,obj_player],
		[cutscene_wait,1],
		[cutscene_dialogue,["I think I lost him...","player",
		"I gotta get out of here.","player"]],
		[cutscene_move_character,obj_player,0,8,true,0.40,spr_player_run,spr_player_idle],
		[cutscene_move_character,obj_player,252,204,false,0.40,spr_player_run,spr_player_idle],
		[cutscene_change_value,obj_light_area,"image_xscale",0],
		[cutscene_wait,0.05],
		[cutscene_change_value,obj_light_area,"image_xscale",150],
		[cutscene_wait,0.05],
		[cutscene_change_value,obj_light_area,"image_xscale",0],
		[cutscene_wait,0.05],
		[cutscene_change_value,obj_light_area,"image_xscale",150],
		[cutscene_wait,0.05],
		[cutscene_change_value,obj_light_area,"image_xscale",0],
		[cutscene_dialogue,["What the heck was that?","player"]],
		[cutscene_wait,0.5],
		[cutscene_change_xscale,obj_player],
		[cutscene_wait,0.5],
		[cutscene_change_xscale,obj_player],
		[cutscene_wait,0.5],
		[cutscene_move_character,obj_player,0,-10,true,0.20,spr_player_walk,spr_player_idle],
		//[cutscene_play_animation,obj_player,spr_player_push_button,spr_player_idle],
		[cutscene_wait,0.5],
		//play click sound
		[cutscene_dialogue,["It won't open. The power must be out.","player",
		"If I can find a breaker room I should be able to get the power back on.","player"]],
		[cutscene_move_character,obj_player,0,6,true,0.20,spr_player_walk,spr_player_idle],
		[cutscene_change_value,obj_progress,"play_lobby_cutscene_1",false],
	]
} else  instance_destroy();

