t_scene_info = [
	[cutscene_instance_create,904,160,"enemies",obj_mimic2],
	[cutscene_play_sound,snd_bgrnd,0.9,true],
	[cutscene_move_character,obj_player,16,0,true,0.15,spr_player_walk,spr_player_idle],
	[cutscene_move_character,obj_mimic2,-45,0,true,0.2,spr_mimic2_run,spr_mimic2_idle],
	[cutscene_change_sprite,obj_player,spr_player_gun_idle,0],
	[cutscene_play_sound,snd_gun_draw,1,false],
	[cutscene_wait,0.5],
	[cutscene_stop_sound,snd_bgrnd],
	[cutscene_dialogue,["Don't take another step!","player",  //dont move?
	"Lily, it's me, Jordan.","jordan",
	"You tried to kill me a minute ago!","player",
	"What are you talking about?","jordan"]],
	[cutscene_move_character,obj_mimic2,-6,0,true,0.1,spr_mimic2_walk,spr_mimic2_idle],
	[cutscene_dialogue,["I said don't move!","player",
	"Lily, I would never hurt you.","jordan",
	"I just need you to put the gun down.","jordan",
	"...","player"]],
	[cutscene_wait,1],
	[cutscene_change_sprite,obj_player,spr_player_idle,0],
	[cutscene_play_sound,snd_gun_holster,1,false],
	[cutscene_wait,0.5],
	[cutscene_move_character,obj_mimic2,-6,0,true,0.1,spr_mimic2_walk,spr_mimic2_idle],
	[cutscene_dialogue,["I'm sorry, I have no idea whats going on.","player",
	"I just want to leave, this place is messed up.","player",
	"Don't worry Lily, I'm here for you.","jordan",
	"Let's get out of here.","player",
	"I found a key here that I think can get us to the breaker room.","jordan",
	"Let's head back to the elevators.","jordan"]],
	[cutscene_change_value,obj_mimic2,"follow",true],
	[cutscene_lock_door,inst_55D3B500],
	[cutscene_activate_layer,"enemies2"],
	[cutscene_activate_layer,"cutscene2"],
	[cutscene_change_obj_layer,par_enemy,"enemies"],
	[cutscene_change_obj_layer,obj_cutscene_trigger,"control"],
]