t_scene_info = [
	[cutscene_instance_create,x+8,y,"lighting",obj_darkness],
	[cutscene_wait,0.025],
	[cutscene_instance_destroy,obj_darkness],
	[cutscene_wait,0.025],
	[cutscene_instance_create,x+8,y,"lighting",obj_darkness],
	[cutscene_wait,0.025],
	[cutscene_instance_destroy,obj_darkness],
	[cutscene_wait,0.025],
	[cutscene_instance_create,x+8,y,"lighting",obj_darkness],
	[cutscene_instance_destroy,obj_mimic2],
	[cutscene_wait,0.025],
	[cutscene_instance_destroy,obj_darkness],
	[cutscene_wait,0.025],
	[cutscene_instance_create,room_width/2,room_height/2,"lighting",obj_darkness],
	[cutscene_change_value,obj_darkness,"image_xscale",1000],
	[cutscene_change_value,obj_darkness,"image_yscale",1000],
	[cutscene_wait,0.5],
	[cutscene_change_xscale,obj_player],
	[cutscene_wait,0.5],
	[cutscene_dialogue,["What the heck was that?","player"]],
	[cutscene_change_xscale,obj_player],
	[cutscene_wait,0.5],
	[cutscene_change_xscale,obj_player],
	[cutscene_dialogue,["Jordan..?","player",
	"Where'd you go?","player"]],
	[cutscene_wait,1],
	[cutscene_change_xscale,obj_player],
	[cutscene_move_character,obj_player,372,440,false,0.25,spr_player_walk,spr_player_idle],
	[cutscene_wait,0.5],
	[cutscene_dialogue,["Damn it! its locked.","player"]],
]